extends Node
## Autoload: TriviaDB

## Autoload singleton containing 50 trivia entries for the Wisdom Totems system.
## Add to Project Settings > Autoload as "TriviaDB".

## Trivia entries grouped by theme index ranges:
##   0-9   Ciencias: Cuerpo y Agua
##   10-19 Animales Nativos
##   20-29 Culturas Andinas (Aymara / Quechua)
##   30-34 Diaguita y Lickanantay
##   35-44 Mapuche
##   45-49 Rapa Nui & Extremo Sur

const TRIVIA_LIST: Array[Dictionary] = [

# ── Ciencias: Cuerpo y Agua (0-9) ──
{"title": "El Motor del Cuerpo", "text": "El coraz\u00f3n bombea la sangre a todo el cuerpo, mientras que los pulmones participan en la respiraci\u00f3n inflando y desinflando el t\u00f3rax.", "q1": "\u00bfQu\u00e9 \u00f3rgano bombea la sangre?", "options1": ["El coraz\u00f3n", "El est\u00f3mago"], "ans1": 0, "q2": "\u00bfQu\u00e9 hacen los pulmones?", "options2": ["Digerir comida", "Participar en la respiraci\u00f3n"], "ans2": 1},
{"title": "La Digestión", "text": "El est\u00f3mago ayuda a digerir los alimentos, transform\u00e1ndolos en trozos m\u00e1s peque\u00f1os para que el cuerpo pueda usarlos.", "q1": "\u00bfCu\u00e1l es la funci\u00f3n del est\u00f3mago?", "options1": ["Transformar los alimentos", "Proteger el coraz\u00f3n"], "ans1": 0, "q2": "\u00bfEn qu\u00e9 se transforman los alimentos?", "options2": ["En agua", "En trozos m\u00e1s peque\u00f1os"], "ans2": 1},
{"title": "Músculos y Huesos", "text": "Los m\u00fasculos son blandos y el\u00e1sticos, y est\u00e1n unidos a los huesos por tendones. Juntos permiten el movimiento de nuestro cuerpo.", "q1": "\u00bfC\u00f3mo son los m\u00fasculos?", "options1": ["Blandos y el\u00e1sticos", "Duros como rocas"], "ans1": 0, "q2": "\u00bfQu\u00e9 une los m\u00fasculos a los huesos?", "options2": ["Los tendones", "La sangre"], "ans2": 0},
{"title": "Agua Pura", "text": "El agua potable es ins\u00edpida, incolora e inodora. Esto significa que no tiene sabor, no tiene color (es transparente) y no tiene olor.", "q1": "\u00bfQu\u00e9 significa inodora?", "options1": ["Que no tiene color", "Que no tiene olor"], "ans1": 1, "q2": "\u00bfQu\u00e9 significa incolora?", "options2": ["Que es transparente", "Que no tiene sabor"], "ans2": 0},
{"title": "El Agua Disolvente", "text": "El agua tiene la capacidad de disolver muchos ingredientes, separ\u00e1ndolos en partes peque\u00f1itas que casi no se ven, como el az\u00facar o la sal.", "q1": "\u00bfQu\u00e9 hace el agua con el az\u00facar?", "options1": ["La disuelve", "La congela"], "ans1": 0, "q2": "\u00bfQu\u00e9 significa disolver?", "options2": ["Separar en partes peque\u00f1as", "Juntar en una gran masa"], "ans2": 0},
{"title": "Estados del Agua", "text": "Con el calor, el agua l\u00edquida se evapora. Con mucho fr\u00edo, se transforma en hielo s\u00f3lido. Si la temperatura es media, se mantiene l\u00edquida.", "q1": "\u00bfQu\u00e9 le pasa al agua con el calor?", "options1": ["Se congela", "Se evapora"], "ans1": 1, "q2": "\u00bfEn qu\u00e9 se transforma con mucho fr\u00edo?", "options2": ["En hielo s\u00f3lido", "En vapor"], "ans2": 0},
{"title": "Precipitaciones", "text": "Cuando el vapor de agua de las nubes se enfr\u00eda, cae a la tierra como precipitaciones. Estas pueden ser lluvia, granizo o nieve.", "q1": "\u00bfDe d\u00f3nde vienen las precipitaciones?", "options1": ["De las nubes fr\u00edas", "Del suelo caliente"], "ans1": 0, "q2": "\u00bfCu\u00e1l es un tipo de precipitaci\u00f3n?", "options2": ["El viento", "El granizo"], "ans2": 1},
{"title": "La Temperatura", "text": "La temperatura nos indica qu\u00e9 tan caliente o fr\u00edo est\u00e1 el ambiente. Se mide en grados Celsius utilizando un term\u00f3metro.", "q1": "\u00bfQu\u00e9 instrumento mide la temperatura?", "options1": ["El pluvi\u00f3metro", "El term\u00f3metro"], "ans1": 1, "q2": "\u00bfEn qu\u00e9 se mide la temperatura?", "options2": ["Grados Celsius", "Kilos"], "ans2": 0},
{"title": "El Viento", "text": "El viento corresponde al movimiento del aire. No podemos verlo, pero lo percibimos al observar los \u00e1rboles moverse o elevar un volant\u00edn.", "q1": "\u00bfQu\u00e9 es el viento?", "options1": ["Agua congelada", "El movimiento del aire"], "ans1": 1, "q2": "\u00bfC\u00f3mo sabemos que hay viento?", "options2": ["Viendo los \u00e1rboles moverse", "Viendo el cielo azul"], "ans2": 0},
{"title": "Ciclos de Vida", "text": "Todos los animales nacen, crecen, se reproducen y mueren. Por ejemplo, los anfibios como las ranas dejan sus huevos en el agua y nacen como renacuajos.", "q1": "\u00bfD\u00f3nde dejan sus huevos las ranas?", "options1": ["En los \u00e1rboles", "En el agua"], "ans1": 1, "q2": "\u00bfC\u00f3mo nacen las ranas?", "options2": ["Como renacuajos", "Con plumas"], "ans2": 0},

# ── Animales Nativos (10-19) ──
{"title": "Ballena Azul", "text": "La ballena azul es un mam\u00edfero nativo marino en peligro de extinci\u00f3n. Las boyas inteligentes en el mar ayudan a evitar que los barcos las da\u00f1en.", "q1": "\u00bfQu\u00e9 tipo de animal es la ballena azul?", "options1": ["Un ave marina", "Un mam\u00edfero marino"], "ans1": 1, "q2": "\u00bfQu\u00e9 tecnolog\u00eda las protege de los barcos?", "options2": ["Boyas inteligentes", "Redes gigantes"], "ans2": 0},
{"title": "Gato Montés Andino", "text": "Es un felino que vive en la Zona Norte de Chile. Lamentablemente, a veces es cazado por perros dom\u00e9sticos que andan sueltos.", "q1": "\u00bfD\u00f3nde vive el gato mont\u00e9s andino?", "options1": ["En la Zona Sur", "En la Zona Norte"], "ans1": 1, "q2": "\u00bfQu\u00e9 amenaza sufre este felino?", "options2": ["Perros dom\u00e9sticos", "Falta de agua salada"], "ans2": 0},
{"title": "El Huemul", "text": "El huemul es un ciervo nativo que habita en la Zona Sur de Chile. Al ser un mam\u00edfero, la hembra alimenta a sus cr\u00edas con leche.", "q1": "\u00bfEn qu\u00e9 zona de Chile vive el huemul?", "options1": ["Zona Norte", "Zona Sur"], "ans1": 1, "q2": "\u00bfC\u00f3mo alimenta a sus cr\u00edas?", "options2": ["Con leche materna", "Con semillas"], "ans2": 0},
{"title": "Ñandú Patagónico", "text": "El \u00f1and\u00fa patag\u00f3nico es un ave corredora de la Zona Sur de Chile. Est\u00e1 en peligro por la caza ilegal y la destrucci\u00f3n de sus nidos.", "q1": "\u00bfEl \u00f1and\u00fa patag\u00f3nico puede volar?", "options1": ["S\u00ed, es un ave de alto vuelo", "No, es un ave corredora"], "ans1": 1, "q2": "\u00bfPor qu\u00e9 est\u00e1 en peligro?", "options2": ["Por la destrucci\u00f3n de sus nidos", "Porque no sabe cazar"], "ans2": 0},
{"title": "Loro Tricahue", "text": "Esta colorida ave vive en la Zona Central de Chile. Muchos de ellos est\u00e1n en peligro porque las personas los venden como mascotas.", "q1": "\u00bfEn qu\u00e9 zona vive el loro tricahue?", "options1": ["Zona Central", "Isla de Pascua"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 es un ave en peligro?", "options2": ["Porque los venden como mascotas", "Porque el viento los arrastra"], "ans2": 0},
{"title": "Tortuga Cabezona", "text": "Es un reptil marino que vive en la costa del Oc\u00e9ano Pac\u00edfico chileno. Su hogar est\u00e1 siendo destruido por la contaminaci\u00f3n por pl\u00e1sticos.", "q1": "\u00bfQu\u00e9 tipo de animal es la tortuga cabezona?", "options1": ["Reptil", "Anfibio"], "ans1": 0, "q2": "\u00bfQu\u00e9 contamina gravemente su hogar?", "options2": ["El barro", "Los pl\u00e1sticos en el oc\u00e9ano"], "ans2": 1},
{"title": "Gruñidor de Valeria", "text": "Es un reptil end\u00e9mico que habita en los bosques de la Zona Central. Los incendios forestales destruyen r\u00e1pidamente su hogar.", "q1": "\u00bfQu\u00e9 destruye el hogar del gru\u00f1idor?", "options1": ["Los incendios forestales", "Las grandes lluvias"], "ans1": 0, "q2": "\u00bfQu\u00e9 debemos hacer para ayudarlo?", "options2": ["Evitar encender fuego en la naturaleza", "Llevarlo a la playa"], "ans2": 0},
{"title": "Rana del Loa", "text": "Este anfibio vive en una vertiente del desierto de Atacama. Se encuentra en peligro cr\u00edtico debido a la grave sequ\u00eda de su h\u00e1bitat.", "q1": "\u00bfD\u00f3nde vive la rana del Loa?", "options1": ["En el desierto de Atacama", "En los bosques del sur"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 est\u00e1 en peligro cr\u00edtico?", "options2": ["Por la falta de alimento", "Por la grave sequ\u00eda"], "ans2": 1},
{"title": "Pez Karachi", "text": "El karachi es un peque\u00f1o pez que habita en la laguna Piacota, en la Zona Norte. Sufre por la disminuci\u00f3n de las lluvias en el altiplano.", "q1": "\u00bfEn qu\u00e9 tipo de agua vive el pez karachi?", "options1": ["En el oc\u00e9ano Pac\u00edfico", "En la laguna Piacota"], "ans1": 1, "q2": "\u00bfQu\u00e9 problema enfrenta este pez?", "options2": ["La disminuci\u00f3n de lluvias", "Los grandes barcos"], "ans2": 0},
{"title": "Invertebrados Nativos", "text": "Animales como la ara\u00f1a pollito, la jaiba marmola, la chinita y el t\u00e1bano negro no tienen columna vertebral. Se les llama invertebrados.", "q1": "\u00bfQu\u00e9 significa ser invertebrado?", "options1": ["No tener columna vertebral", "No saber nadar"], "ans1": 0, "q2": "\u00bfCu\u00e1l de estos es un invertebrado?", "options2": ["El Huemul", "La jaiba marmola"], "ans2": 1},

# ── Culturas Andinas: Aymara y Quechua (20-29) ──
{"title": "Cultura Aymara", "text": "Para el pueblo Aymara, la naturaleza es sagrada. Los cerros o Mallku son sus protectores, y las vertientes o Phuju son los ojos de la tierra.", "q1": "\u00bfQu\u00e9 son los Mallku?", "options1": ["R\u00edos correntosos", "Cerros protectores"], "ans1": 1, "q2": "\u00bfQu\u00e9 significa Phuju?", "options2": ["Vertiente de agua", "Desierto seco"], "ans2": 0},
{"title": "El Willka Kuti", "text": "El 21 de junio, las comunidades aymara celebran el Willka Kuti (Retorno del Sol). Se espera el amanecer con las manos en alto para recibir su energ\u00eda.", "q1": "\u00bfCu\u00e1ndo se celebra el Willka Kuti?", "options1": ["21 de Diciembre", "21 de Junio"], "ans1": 1, "q2": "\u00bfQu\u00e9 significa Willka Kuti?", "options2": ["Retorno del Sol", "Fiesta de la Luna"], "ans2": 0},
{"title": "Qarwa Wayñu", "text": "El Qarwa Way\u00f1u es la fiesta aymara de los llamos. Se agradece a la Pachamama adornando las orejas de los animales con zarcillos (sarsillu) de lanas de colores.", "q1": "\u00bfA qu\u00e9 animal se celebra en el Qarwa Way\u00f1u?", "options1": ["A la gaviota", "A la llama"], "ans1": 1, "q2": "\u00bfC\u00f3mo se adornan los animales?", "options2": ["Con zarcillos de lanas", "Con pintura roja"], "ans2": 0},
{"title": "El Ayni", "text": "El Ayni es el principio andino de ayuda mutua o reciprocidad. Nos ense\u00f1a que debemos colaborar y compartir el trabajo en comunidad.", "q1": "\u00bfQu\u00e9 valor promueve el Ayni?", "options1": ["La ayuda mutua", "Competir contra otros"], "ans1": 0, "q2": "\u00bfQu\u00e9 le pasa a quienes no practican el Ayni?", "options2": ["Quedan solos y sin apoyo", "Se vuelven l\u00edderes"], "ans2": 0},
{"title": "Pisos Ecológicos", "text": "Los aymaras viven en diferentes pisos ecol\u00f3gicos: Suni Pata (altiplano), Qhirwa Pata (valles) y Quta Thiya (costa), adaptando sus cultivos a cada clima.", "q1": "\u00bfQu\u00e9 es Suni Pata?", "options1": ["El Altiplano", "La costa marina"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 viajan entre los pisos ecol\u00f3gicos?", "options2": ["Para intercambiar productos", "Para buscar oro"], "ans2": 0},
{"title": "La Wiphala", "text": "La Wiphala es el emblema de las culturas andinas. Tiene forma de cuadrados y lleva 7 colores que representan la naturaleza y el universo.", "q1": "\u00bfCu\u00e1ntos colores tiene la Wiphala?", "options1": ["Siete colores", "Tres colores"], "ans1": 0, "q2": "\u00bfQu\u00e9 representa el color rojo en la Wiphala?", "options2": ["La Madre Tierra", "El oc\u00e9ano profundo"], "ans2": 0},
{"title": "La Chakana", "text": "La Chakana o Cruz Andina representa la uni\u00f3n entre el cielo y la tierra. Su forma de escalera escalonada se basa en la observaci\u00f3n de las estrellas.", "q1": "\u00bfQu\u00e9 otra forma de llamarle tiene la Chakana?", "options1": ["Cruz Andina", "C\u00edrculo Lunar"], "ans1": 0, "q2": "\u00bfEn qu\u00e9 se basaron para crear su forma?", "options2": ["En las nubes", "En la observaci\u00f3n de las estrellas"], "ans2": 1},
{"title": "El Inti Raymi", "text": "El pueblo Quechua celebra el Inti Raymi o Fiesta del Sol en junio. Agradecen por la buena cosecha, la salud y piden favores a la Pachamama.", "q1": "\u00bfQu\u00e9 se celebra en el Inti Raymi?", "options1": ["La Fiesta del Agua", "La Fiesta del Sol"], "ans1": 1, "q2": "\u00bfA qui\u00e9n se dirigen los agradecimientos y ofrendas?", "options2": ["A la Pachamama", "A los espa\u00f1oles"], "ans2": 0},
{"title": "Cultivos en Terrazas", "text": "Los quechuas aprendieron de los Incas a cultivar en las laderas de los cerros construyendo terrazas de piedra para aprovechar mejor el agua.", "q1": "\u00bfD\u00f3nde se construyen las terrazas de cultivo?", "options1": ["En las laderas de los cerros", "En el fondo del mar"], "ans1": 0, "q2": "\u00bfQu\u00e9 cultura invent\u00f3 esta forma de cultivar?", "options2": ["Los Incas", "Los Chonos"], "ans2": 0},
{"title": "El Grano de Oro", "text": "La quinua es considerada el 'grano de oro' de los Andes por ser un alimento muy nutritivo y sagrado para los pueblos aymara y quechua.", "q1": "\u00bfC\u00f3mo le llaman a la quinua?", "options1": ["El grano de oro", "La hoja m\u00e1gica"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 es tan valorada la quinua?", "options2": ["Es muy nutritiva", "Porque brilla en la oscuridad"], "ans2": 0},

# ── Diaguita y Lickanantay (30-34) ──
{"title": "El Pueblo Diaguita", "text": "Los diaguitas habitaron los valles de la Zona Norte. Eran grandes artesanos y decoraban sus vasijas con formas geom\u00e9tricas y figuras de animales.", "q1": "\u00bfEn qu\u00e9 zona de Chile vivi\u00f3 el pueblo Diaguita?", "options1": ["Zona Norte", "Zona Sur"], "ans1": 0, "q2": "\u00bfC\u00f3mo decoraban sus cer\u00e1micas?", "options2": ["Con formas geom\u00e9tricas", "Pint\u00e1ndolas solo de azul"], "ans2": 0},
{"title": "El Jarro Pato", "text": "Una de las creaciones m\u00e1s famosas del pueblo Diaguita es el Jarro Pato, una vasija de cer\u00e1mica hecha con greda que serv\u00eda para ceremonias y uso diario.", "q1": "\u00bfCon qu\u00e9 material se hace el Jarro Pato?", "options1": ["Madera", "Greda o cer\u00e1mica"], "ans1": 1, "q2": "\u00bfPara qu\u00e9 lo usaban principalmente?", "options2": ["Como instrumento musical", "Para ceremonias y uso diario"], "ans2": 1},
{"title": "Colores Naturales", "text": "Para pintar sus cer\u00e1micas, los diaguitas usaban colores hechos con minerales, tierra y plantas locales como el algarrobo. Usaban rojo, blanco y negro.", "q1": "\u00bfDe d\u00f3nde sacaban los colores para pintar?", "options1": ["De minerales y plantas", "De animales marinos"], "ans1": 0, "q2": "\u00bfCu\u00e1les eran sus colores preferidos?", "options2": ["Verde y morado", "Rojo, blanco y negro"], "ans2": 1},
{"title": "Pueblo Lickanantay", "text": "Los Lickanantay o atacame\u00f1os habitaban el desierto m\u00e1s \u00e1rido del mundo. Construyeron fortalezas de piedra llamadas Pukar\u00e1s para protegerse.", "q1": "\u00bfC\u00f3mo se llamaban las fortalezas del pueblo Lickanantay?", "options1": ["Rucas", "Pukar\u00e1s"], "ans1": 1, "q2": "\u00bfDe qu\u00e9 material estaban hechos los Pukar\u00e1s?", "options2": ["De madera", "De piedra"], "ans2": 1},
{"title": "Petroglifos", "text": "Tanto diaguitas como lickanantay dejaron mensajes tallados en las piedras llamados petroglifos, donde dibujaban llamas, el sol y cazadores.", "q1": "\u00bfQu\u00e9 es un petroglifo?", "options1": ["Un mensaje tallado en la roca", "Un tipo de vasija"], "ans1": 0, "q2": "\u00bfQu\u00e9 sol\u00edan dibujar en los petroglifos?", "options2": ["Llamas y el sol", "Olas del mar"], "ans2": 0},

# ── Mapuche (35-44) ──
{"title": "Wiñol Txipantu", "text": "El Wi\u00f1ol Txipantu marca el inicio del a\u00f1o mapuche durante el solsticio de invierno. Significa 'el retorno del sol' o el regreso de los d\u00edas m\u00e1s largos.", "q1": "\u00bfQu\u00e9 significa Wi\u00f1ol Txipantu?", "options1": ["El retorno del sol", "La gran lluvia"], "ans1": 0, "q2": "\u00bfEn qu\u00e9 \u00e9poca del a\u00f1o ocurre?", "options2": ["Solsticio de verano", "Solsticio de invierno"], "ans2": 1},
{"title": "El Küpam", "text": "El K\u00fcpam es una prenda de lana negra que cubre el cuerpo de la mujer mapuche. Se usa el negro para pedir lluvia y fertilidad a la tierra.", "q1": "\u00bfQui\u00e9n usa el K\u00fcpam?", "options1": ["Los guerreros", "Las mujeres mapuche"], "ans1": 1, "q2": "\u00bfPor qu\u00e9 la tela suele ser de color negro?", "options2": ["Para pedir lluvia y fertilidad", "Para esconderse en la noche"], "ans2": 0},
{"title": "Meli Witxan Mapu", "text": "Para el pueblo Mapuche, el mundo se divide en cuatro grandes territorios: Puel Mapu (Este), Pikun Mapu (Norte), Willi Mapu (Sur) y Lafken Mapu (Mar).", "q1": "\u00bfEn cu\u00e1ntos territorios dividen el mundo los mapuche?", "options1": ["Dos territorios", "Cuatro territorios"], "ans1": 1, "q2": "\u00bfQu\u00e9 representa el Lafken Mapu?", "options2": ["La zona de las monta\u00f1as", "La zona del mar"], "ans2": 1},
{"title": "Los Rütxafe", "text": "Los r\u00fctxafe son los orfebres o joyeros mapuche. Trabajan la plata creando hermosos adornos como el chaway (aros) y la trapelacucha.", "q1": "\u00bfQu\u00e9 oficio tiene un r\u00fctxafe?", "options1": ["Trabajar la plata", "Cultivar la tierra"], "ans1": 0, "q2": "\u00bfQu\u00e9 significa la palabra chaway?", "options2": ["Zapatos", "Aros de plata"], "ans2": 1},
{"title": "El Piñoneo", "text": "El pi\u00f1\u00f3n o g\u00fclliw es el fruto de la araucaria. Para recolectarlos en oto\u00f1o, las familias usan un lazo llamado lh\u00fckay para hacer caer las pi\u00f1as maduras.", "q1": "\u00bfDe qu\u00e9 \u00e1rbol viene el pi\u00f1\u00f3n?", "options1": ["Del roble", "De la araucaria"], "ans1": 1, "q2": "\u00bfC\u00f3mo se llama el lazo para hacerlos caer?", "options2": ["Trariwe", "Lh\u00fckay"], "ans2": 1},
{"title": "El Juego del Palin", "text": "El palin es un juego tradicional mapuche donde dos equipos usan bastones de madera (wi\u00f1o) para golpear una bola. Se hace para compartir y celebrar.", "q1": "\u00bfQu\u00e9 se usa para jugar al palin?", "options1": ["Arcos y flechas", "Bastones de madera y una bola"], "ans1": 1, "q2": "\u00bfPara qu\u00e9 se juega al palin principalmente?", "options2": ["Para castigar", "Para compartir y celebrar"], "ans2": 1},
{"title": "Treng Treng y Kai Kai", "text": "Cuenta el epew (relato) que dos grandes serpientes lucharon: Kai Kai inund\u00f3 la tierra con agua, y Treng Treng elev\u00f3 los cerros para salvar a las personas.", "q1": "\u00bfQu\u00e9 hizo la serpiente Kai Kai?", "options1": ["Inund\u00f3 la tierra con agua", "Sopl\u00f3 fuego"], "ans1": 0, "q2": "\u00bfQui\u00e9n salv\u00f3 a las personas elevando los cerros?", "options2": ["Treng Treng", "El C\u00f3ndor"], "ans2": 0},
{"title": "El Abuelito Huentellao", "text": "En San Juan de la Costa, los mapuche williche piden permiso al esp\u00edritu del Abuelito Huentellao antes de ir a recolectar mariscos al mar.", "q1": "\u00bfQui\u00e9n es el Abuelito Huentellao?", "options1": ["El protector del mar", "Un rey Inca"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 le piden permiso los pescadores?", "options2": ["Para no enfermarse", "Para tener buena pesca y recolecci\u00f3n"], "ans2": 1},
{"title": "Las Dalcas", "text": "Las dalcas eran canoas ligeras usadas por los mapuche williche y los chonos en Chilo\u00e9. Se constru\u00edan cosiendo tres tablones de madera con fibras vegetales.", "q1": "\u00bfQu\u00e9 es una dalca?", "options1": ["Una casa de madera", "Una canoa ligera de tres tablones"], "ans1": 1, "q2": "\u00bfC\u00f3mo se un\u00edan los tablones de madera?", "options2": ["Con clavos de metal", "Cosi\u00e9ndolos con fibras vegetales"], "ans2": 1},
{"title": "El Trafkintu", "text": "El Trafkintu es el intercambio tradicional mapuche. No usaban dinero, sino que intercambiaban semillas, animales o conocimientos para apoyarse mutuamente.", "q1": "\u00bfEn qu\u00e9 consiste el Trafkintu?", "options1": ["En intercambiar bienes sin usar dinero", "En vender productos caros"], "ans1": 0, "q2": "\u00bfPor qu\u00e9 realizaban el Trafkintu?", "options2": ["Para apoyarse mutuamente y compartir", "Para hacerse ricos"], "ans2": 0},

# ── Rapa Nui & Extremo Sur (45-49) ──
{"title": "Los Ahu de Rapa Nui", "text": "Los ahu son grandes plataformas rectangulares de piedra construidas cerca de la costa, sobre las cuales el pueblo Rapa Nui instalaba a sus gigantescos Moais.", "q1": "\u00bfQu\u00e9 es un ahu?", "options1": ["Una canoa polin\u00e9sica", "Una plataforma rectangular de piedra"], "ans1": 1, "q2": "\u00bfQu\u00e9 se instalaba sobre los ahu?", "options2": ["Los Moais", "Las redes de pesca"], "ans2": 0},
{"title": "El Rey Hotu Matu'a", "text": "Seg\u00fan la tradici\u00f3n de Rapa Nui, el primer Ariki (rey) en llegar a la isla fue Hotu Matu'a, quien desembarc\u00f3 en la playa de Anakena tras un largo viaje.", "q1": "\u00bfC\u00f3mo se llamaba el primer Ariki de Rapa Nui?", "options1": ["Hotu Matu'a", "Tu'u Koihu"], "ans1": 0, "q2": "\u00bfEn qu\u00e9 playa habr\u00eda desembarcado?", "options2": ["Playa de Anakena", "Vi\u00f1a del Mar"], "ans2": 0},
{"title": "Observar las Estrellas", "text": "La piedra 'Papa U'i Hetu'u' en Rapa Nui tiene grabados del cielo. Mirar las estrellas ayudaba a los navegantes a saber cu\u00e1ndo plantar y cu\u00e1ndo pescar.", "q1": "\u00bfPara qu\u00e9 observaban las estrellas los antiguos Rapa Nui?", "options1": ["Para saber cu\u00e1ndo plantar y pescar", "Para adivinar la suerte"], "ans1": 0, "q2": "\u00bfQu\u00e9 significa Papa U'i Hetu'u?", "options2": ["Volc\u00e1n gigante", "Piedra para observar las estrellas"], "ans2": 1},
{"title": "Corrales de Pesca", "text": "Pueblos del sur como los Chono construyeron corrales de pesca. Eran muros de piedra en la costa donde los peces quedaban atrapados al bajar la marea.", "q1": "\u00bfQu\u00e9 es un corral de pesca?", "options1": ["Un muro de piedra en la costa para atrapar peces", "Una red para atrapar aves"], "ans1": 0, "q2": "\u00bfCu\u00e1ndo quedaban atrapados los peces?", "options2": ["Al subir la marea", "Al bajar la marea"], "ans2": 1},
{"title": "Fuego en las Canoas", "text": "El pueblo Yag\u00e1n navegaba por los canales helados del sur. Llevaban fuego encendido sobre tierra o piedras dentro de sus canoas para cocinar y calentarse.", "q1": "\u00bfQu\u00e9 llevaban encendido dentro de sus canoas los Yaganes?", "options1": ["Antorchas el\u00e9ctricas", "Fuego sobre tierra o piedras"], "ans1": 1, "q2": "\u00bfPara qu\u00e9 usaban ese fuego en las canoas?", "options2": ["Para calentarse y cocinar", "Para iluminar el cielo"], "ans2": 0},
]


func _ready() -> void:
	print("TriviaDB: ", TRIVIA_LIST.size(), " entries loaded")
